copyright: Copyright &copy; 2015-2021 THOORENS Bruno - BSD licence
docs_dir: docs
nav:
- Home: index.md
- API: api.md
- Geodesy: geodesy.md
- Grids: grids.md
repo_name: GitHub
repo_url: https://github.com/Moustikitos/Gryd
site_name: The Gryd Project
theme: mkdocs
